# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [3]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

def check_first_last(arr):
    if arr[0] == arr[len(arr)-1]:
        return True
    else:
        return False
    
check_first_last(numbers_x)

True





# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [7]:
#code here
import numpy as np

arr1 = np.array([10, 20, 30, 40, 10])
arr2 = np.array([75, 65, 35, 75, 30])

sum = np.sum(arr1+arr2)

print("Sum is: ", sum)

product = np.product(arr1*arr2)

print("Product is: ",product)

Sum is:  390
Product is:  1435792896


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [46]:
#code here

arr_1d = [1,2,3,4,5,6,7,8,9,10,11,12]

arr_3x4 = np.reshape(arr_1d,(3,4))

print(arr_3x4,"\n")

arr1 = np.array([[1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4]])



arr_horizontally_stacked = np.hstack([arr_3x4,arr1])

print("Horizontally stacked: \n\n",arr_horizontally_stacked, "\n\n")

arr_1d = [1,2,3,4,5,6,7,8,9,10,11,12]

arr_3x4 = np.reshape(arr_1d,(3,4))


arr1 = np.array([[1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4]])

arr_vertically_stacked = np.vstack([arr_3x4,arr1])

print("Vertically stacked: \n\n",arr_vertically_stacked, "\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Horizontally stacked: 

 [[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  1  2  3  4]
 [ 9 10 11 12  1  2  3  4]] 


Vertically stacked: 

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 1  2  3  4]
 [ 1  2  3  4]] 



# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [58]:
#Code here

shopping_cart = []

i = 0
while(True):
    if i == 0:
        print("Welcome to Online Shopping.\n")
        print("Here are the available products. Chose your product:\n")
        print("1.Keyboard - $200\n")
        print("2.Mouse - $50\n")
        print("3.Monitor - $300\n")
    items = ["Keyboard - $200","Mouse - $50","Monitor - $300"]

    user_input = input()
    if user_input == '1' or user_input == '2' or user_input == '3':
        print("Item ",items[int(user_input) - 1]," successfully added to the cart.\n")
        shopping_cart.append(items[int(user_input) - 1])
        print("To continue shopping, chose more items. To Exit, press q.\n")
    elif user_input == 'q':
        break
    else:
        print("Wrong input. Try again. \n")
    i+=1


print("Here is what your shopping cart contains: ")
for i in range(len(shopping_cart)):
    print(i,". ",shopping_cart[i])

Welcome to Online Shopping.

Here are the available products. Chose your product:

1.Keyboard - $200

2.Mouse - $50

3.Monitor - $300

Item  Keyboard - $200  successfully added to the cart.

To continue shopping, chose more items. To Exit, press q.

Item  Mouse - $50  successfully added to the cart.

To continue shopping, chose more items. To Exit, press q.

Here is what your shopping cart contains: 
0 .  Keyboard - $200
1 .  Mouse - $50


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [68]:
#code here

email1 = "Hello this is promotion for our company Stylish Cars. You can get the best deals for some of the best sports cars. Get our coupon codes and dont forget to get a discount."
email2 = "Dear student, your attention is required. You are thereby informed of an important event that is coming regarding the innovations in the AI field. We strongly recommend that you must attend this event."
email3 = "Congratulations!!! You have won a million dollars. Click here to open the link, enter your bank account details and get your million dollar cash instantly before the link expires."

emails = []

emails.append(email1)
emails.append(email2)
emails.append(email3)

spam_keywords = ["million","dollars","won","account","bank","link","checkout","prize","lottery","congratulations"]
important_keywords = ["attention","important","must","strongly","recommend","thereby","informed","reminder"]
promotion_keywords = ["promotion","discount","offer","deals","best","coupon"]

word_match_treshold = 3

def check_spam_promotion_important(emails):
    i = 0
    spam_words = 0
    important_words = 0
    promotion_words = 0
    for email in emails:
        email_tokens = email.replace(",","").replace(".","").split()
        for word in email_tokens:
            if word in spam_keywords:
                spam_words +=1
                if spam_words >= word_match_treshold:
                    print("Email#",i," is detected to be a SPAM.")
                    break
            elif word in important_keywords:
                important_words +=1
                if important_words >= word_match_treshold:
                    print("Email#",i," is detected to be an Important Email.")
                    break
            elif word in promotion_keywords:
                promotion_words +=1
                if promotion_words >= word_match_treshold:
                    print("Email#",i," is detected to be a Promotional Email.")
                    break
        i+=1

check_spam_promotion_important(emails)

Email# 0  is detected to be a Promotional Email.
Email# 1  is detected to be an Important Email.
Email# 2  is detected to be a SPAM.


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [69]:
#code here

english_urdu_dictionary = {"Welcome":"خوشآمدید","Nice":"اچھا", "Roof":"چھت", "Friend":"دوست", "Best":"بہترین", "Car":"گھاڑی", "Man":"آدمی", "Cat":"بلی", "Dog":"کتا", "Eye":"آنکھ"}

while(True):
    found_word = False
    user_input = input("Enter English Word to see translation. Press q to exit.")
    if user_input == 'q':
        break
    else:
        for key,value in english_urdu_dictionary.items():
            if user_input == key:
                print("Translation for the Word: ",value)
                found_word = True
        if found_word == False:
            print("Word not found in dictionary.")

        

Translation for the Word:  خوشآمدید
Translation for the Word:  خوشآمدید
Translation for the Word:  اچھا
Translation for the Word:  چھت
Translation for the Word:  چھت


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [78]:
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [97]:
import pandas as pd

df = pd.read_csv("vgsalesGlobale.csv")

#Total global sales

sum_global_sales = df["Global_Sales"].sum()

print("Sum of total global sales: ",sum_global_sales)

#finding the game with highest global sales

print("The game with the highest global sales is: ")

index_for_highest_global_sales = df["Global_Sales"].idxmax()

print(df.iloc[index_for_highest_global_sales]["Name"])

print("Average sales for NA: ", df["NA_Sales"].mean())
print("Average sales for JP: ", df["JP_Sales"].mean())
print("Average sales for EU: ", df["EU_Sales"].mean())
print("Average sales for Other Regions: ", df["Other_Sales"].mean())


df = df.sort_values(by="Global_Sales",ascending=False)

print("Top 5 most popular Genres are: ")

top_5 = df.head(5)

print("1.",top_5.iloc[0]["Genre"])
print("2.",top_5.iloc[1]["Genre"])
print("3.",top_5.iloc[2]["Genre"])
print("4.",top_5.iloc[3]["Genre"])
print("5.",top_5.iloc[4]["Genre"])


Sum of total global sales:  8920.44
The game with the highest global sales is: 
Wii Sports
Average sales for NA:  0.26466742981082064
Average sales for JP:  0.077781660441017
Average sales for EU:  0.14665200626581515
Average sales for Other Regions:  0.0480630196409206
Top 5 most popular Genres are: 
1. Sports
2. Platform
3. Racing
4. Sports
5. Role-Playing


In [102]:
grouped = df.groupby("Genre")


print("Total sales for each Genre in each Region:")

for group_name,group in grouped:
    print("For Genre: ",group_name)
    print("Sales in NA: ", group["NA_Sales"].sum())
    print("Sales in EU: ", group["EU_Sales"].sum())
    print("Sales in JP: ", group["JP_Sales"].sum())


Total sales for each Genre in each Region:
For Genre:  Action
Sales in NA:  877.8300000000002
Sales in EU:  525.0
Sales in JP:  159.95000000000002
For Genre:  Adventure
Sales in NA:  105.79999999999998
Sales in EU:  64.13
Sales in JP:  52.06999999999999
For Genre:  Fighting
Sales in NA:  223.59
Sales in EU:  101.32000000000001
Sales in JP:  87.35
For Genre:  Misc
Sales in NA:  410.24
Sales in EU:  215.98000000000002
Sales in JP:  107.75999999999999
For Genre:  Platform
Sales in NA:  447.04999999999995
Sales in EU:  201.63
Sales in JP:  130.77
For Genre:  Puzzle
Sales in NA:  123.77999999999999
Sales in EU:  50.779999999999994
Sales in JP:  57.31
For Genre:  Racing
Sales in NA:  359.41999999999996
Sales in EU:  238.39
Sales in JP:  56.68999999999999
For Genre:  Role-Playing
Sales in NA:  327.28000000000003
Sales in EU:  188.05999999999997
Sales in JP:  352.31
For Genre:  Shooter
Sales in NA:  582.6
Sales in EU:  313.27
Sales in JP:  38.28
For Genre:  Simulation
Sales in NA:  183.3099999

In [103]:
df.tail(10)

Rank                                             Name Platform  \
16181  16184                             Resistance Dual Pack      PS3   
16182  16185                                  Princess Arthur      PSP   
16183  16186                      Sakura-Sou no Pet na Kanojo      PSP   
16184  16187  Fatal Fury: Battle Archives Volume 2 (JP sales)      PS2   
16185  16188           Tantei Jinguuji Saburo: Hai to Diamond      PSP   
16186  16189                                      BattleForge       PC   
16187  16190                                   Jewel Quest II       PC   
16188  16191                                 Toro to Morimori      PS3   
16189  16192             Sonic & All-Stars Racing Transformed       PC   
16597  16600                                 Spirits & Spells      GBA   

         Year      Genre                    Publisher  NA_Sales  EU_Sales  \
16181  2011.0    Shooter  Sony Computer Entertainment      0.00      0.01   
16182  2013.0       Misc                 Idea Factory      0.00      0.00   
16183  2013.0  Adventure               Kadokawa Games      0.00      0.00   
16184  2007.0   Fighting                 SNK Playmore      0.00      0.00   
16185  2009.0  Adventure             Arc System Works      0.00      0.00   
16186  2009.0   Strategy              Electronic Arts      0.00      0.01   
16187  2007.0     Puzzle                    Avanquest      0.00      0.01   
16188  2009.0       Misc  Sony Computer Entertainment      0.00      0.00   
16189  2013.0     Racing                         Sega      0.00      0.01   
16597  2003.0   Platform                      Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16181      0.00          0.0          0.01  
16182      0.01          0.0          0.01  
16183      0.01          0.0          0.01  
16184      0.01          0.0          0.01  
16185      0.01          0.0          0.01  
16186      0.00          0.0          0.01  
16187      0.00          0.0          0.01  
16188      0.01          0.0          0.01  
16189      0.00          0.0          0.01  
16597      0.00          0.0          0.01